# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SQLAlchemy bind manager
theme:
  name: material

nav:
  - Home: index.md
  - Bind manager:
      - Configuration: manager/config.md
      - Models setup: manager/models.md
      - Session usage: manager/session.md
  - Repository:
      - Repository usage: repository/repository.md
      - Unit of work: repository/uow.md

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.details
