# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SQLAlchemy bind manager
site_description: 'A manager to easily handle multiple SQLAlchemy configurations'
site_author: 'Federico Busetti'
docs_dir: docs/
repo_name: 'febus982/sqlalchemy-bind-manager'
repo_url: 'https://github.com/febus982/sqlalchemy-bind-manager'

theme:
  name: material

nav:
  - Home: index.md
  - Bind manager:
      - Configuration: manager/config.md
      - Models setup: manager/models.md
      - Session usage: manager/session.md
  - Repository:
      - Repository usage: repository/repository.md
      - Unit of work: repository/uow.md

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.details
