# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SQLAlchemy bind manager
site_description: 'A manager to easily handle multiple SQLAlchemy configurations'
site_author: 'Federico Busetti'
docs_dir: docs/
repo_name: 'febus982/sqlalchemy-bind-manager'
repo_url: 'https://github.com/febus982/sqlalchemy-bind-manager'

theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/febus982/sqlalchemy-bind-manager
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/federico-b-a0b78232

nav:
  - Home: index.md
  - Bind manager:
      - Configuration: manager/config.md
      - Models setup: manager/models.md
      - Session usage: manager/session.md
      - Alembic: manager/alembic.md
  - Repository:
      - Repository usage: repository/repository.md
      - Unit of work: repository/uow.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.snippets
  - pymdownx.superfences
