[tool.poetry]
name = "sqlalchemy-bind-manager"
version = "0.1.0"
description = ""
authors = ["Federico Busetti <729029+febus982@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "sqlalchemy_bind_manager"}]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.10.2"
SQLAlchemy = { version = "~1.4.43", extras = ["asyncio", "mypy"] }

[tool.poetry.group.dev.dependencies]
coverage = "~6.5.0"
black = "~22.10.0"
flake8 = "~5.0.4"
mypy = "~0.990"
pytest = "~7.2.0"
pytest-cov = "^4.0.0"
pytest-factoryboy = "~2.5.0"
pytest-xdist = "^3.0.2"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
