name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  site:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-github-pages.yml
    with:
      site-version: "dev"
